### ISSUE TITLE
Closing stream while receiving audio from Dialogflow

### ISSUE THREAD

**Issue by JorgMuskens** [nimbleape/asterisk-dialogflow-rtp-audioserver#11]
Hi Dan,
I found another issue when i hnagup x-lite or mobile while the stream is handeling the incoming audio stream it throws an error. This same error also occurs when you do not say anything on the stream. Below the error received

````
{"level":30,"time":1585148812032,"pid":25561,"hostname":"tron-asterisk","name":"Dialogflow-AudioServer","id":"1585148807.80","msg":"Destroying DialogFlow stream","v":1}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at PassThrough.Writable.write (_stream_writable.js:286:11)
    at Timeout._onTimeout (/usr/src/asterisk-dialogflow-rtp-audioserver/lib/DialogFlowConnector.js:170:46)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on PassThrough instance at:
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at PassThrough.Writable.write (_stream_writable.js:310:5)
    at Timeout._onTimeout (/usr/src/asterisk-dialogflow-rtp-audioserver/lib/DialogFlowConnector.js:170:46)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

````

**Comment by JorgMuskens** [comment]
Duplicate issue as it is already in your list sorry closing this now
